eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#     下面为使用集群eureka Server
      defaultZone: http://peer1:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-eurekaclient
